#!/bin/bash
#Example of how to set the environment variables in the reltrans MODEL:
#In order to set the env variable: source example_set_reltrans_env

export REV_VERB=0
export MU_ZONES=1
export ION_ZONES=1
export A_DENSITY=1
export EMIN_REF=0.3
export EMAX_REF=10.0
export EMIN_REF2=0.3
export EMAX_REF2=10.0
export SEED_SIM=-2851043
export BACKSCL=1.0 
export RMF_SET=/path_of_the_first_response/name_of_the_first_response.rmf
export ARF_SET=/path_of_the_first_response/name_of_the_first_response.arf
export RMF_SET2=/path_of_the_second_response/name_of_the_second_response.rmf
export ARF_SET2=/path_of_the_second_response/name_of_the_second_response.arf

